name: firebase_phone_auth_testing
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0+2

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: 1.0.5
  flutter_riverpod: 2.3.6
  riverpod_annotation: 2.1.1
  freezed_annotation: 2.2.0
  json_annotation: 4.8.1
  go_router: 9.0.0
  flutter_secure_storage: 8.0.0
  fpdart: 0.6.0
  intl: 0.18.0
  google_fonts: 5.1.0
  flutter_svg: 2.0.7
  pin_code_fields: 8.0.1
  package_info_plus: 4.0.2
  flutter_animate: 4.2.0
  flutter_multi_formatter: 2.11.1
  shared_preferences: 2.2.0
  firebase_core: 2.14.0
  firebase_auth: 4.6.3
  logger: 1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0
  flutter_launcher_icons: 0.13.1
  custom_lint: 0.4.0
  riverpod_lint: 1.3.2
  build_runner: 2.4.6
  riverpod_generator: 2.2.3
  freezed: 2.3.5
  json_serializable: 6.7.1
  change_app_package_name: 1.1.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/svgs/
