// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCteUILk58xPgReCMe7sU-7TqaWGjDKmS4',
    appId: '1:277905172931:web:1c9b697938be13ec90b576',
    messagingSenderId: '277905172931',
    projectId: 'fir-phone-auth-testing',
    authDomain: 'fir-phone-auth-testing.firebaseapp.com',
    storageBucket: 'fir-phone-auth-testing.appspot.com',
    measurementId: 'G-Q2YSV7N2JC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZpKObks8nC7hKlda6NzgMyk_efmXs2aQ',
    appId: '1:277905172931:android:b457422dd9e1f44090b576',
    messagingSenderId: '277905172931',
    projectId: 'fir-phone-auth-testing',
    storageBucket: 'fir-phone-auth-testing.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACHvx9nn8bR-VmrR62dOC9o2tUbbqHzis',
    appId: '1:277905172931:ios:89fc4931c8dc4e0690b576',
    messagingSenderId: '277905172931',
    projectId: 'fir-phone-auth-testing',
    storageBucket: 'fir-phone-auth-testing.appspot.com',
    iosClientId: '277905172931-7qma0nta2rsf90ukdvqck360b7e0rdoe.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasePhoneAuthTesting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACHvx9nn8bR-VmrR62dOC9o2tUbbqHzis',
    appId: '1:277905172931:ios:eaa80fe09c5a24e090b576',
    messagingSenderId: '277905172931',
    projectId: 'fir-phone-auth-testing',
    storageBucket: 'fir-phone-auth-testing.appspot.com',
    iosClientId: '277905172931-7618dvfr8b8ql8kgchnhm11nq406242p.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasePhoneAuthTesting.RunnerTests',
  );
}
